# Generated by Django 4.2.23 on 2025-07-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='primary_building',
            field=models.CharField(choices=[('EM', 'Empty'), ('GH', 'Great Hall'), ('MK', 'Market'), ('MN', 'Monastery'), ('LP', 'Longphort')], default='EM', max_length=2),
        ),
    ]
